import type { NutrientStandard } from '../types';

export const OCTOBER_STANDARDS_CONFIG: NutrientStandard[] = [
  {
    key: 'N',
    displayName: 'Nitrogen (Total)',
    unit: '%',
    referenceRange: '1.31 – 2.40 %',
    isSafeLimit: false,
    refMin: 1.31,
    refMax: 2.40,
    description: 'Essential for vegetative canopy development and overall vine vigor.',
  },
  {
    key: 'NO3',
    displayName: 'Nitrate (NO3)',
    unit: 'ppm',
    referenceRange: '700 – 1200 ppm',
    isSafeLimit: false,
    refMin: 700,
    refMax: 1200,
    description: 'Mobile inorganic nitrogen form absorbed readily by grape root systems.',
  },
  {
    key: 'NH4_N',
    displayName: 'Ammonium-N (NH4-N)',
    unit: 'ppm',
    referenceRange: '500 – 800 ppm',
    isSafeLimit: false,
    refMin: 500,
    refMax: 800,
    description: 'Directly assimilable nitrogen form; crucial during early shoot growth.',
  },
  {
    key: 'P',
    displayName: 'Phosphorus (P)',
    unit: '%',
    referenceRange: '0.41 – 0.80 %',
    isSafeLimit: false,
    refMin: 0.41,
    refMax: 0.80,
    description: 'Fuels cellular energy transfer (ATP), cluster development, and root expansion.',
  },
  {
    key: 'K',
    displayName: 'Potassium (K)',
    unit: '%',
    referenceRange: '1.11 – 2.20 %',
    isSafeLimit: false,
    refMin: 1.11,
    refMax: 2.20,
    description: 'Key osmotic regulator, berry sugar accumulation, and winter hardiness booster.',
  },
  {
    key: 'Ca',
    displayName: 'Calcium (Ca)',
    unit: '%',
    referenceRange: '0.74 – 1.14 %',
    isSafeLimit: false,
    refMin: 0.74,
    refMax: 1.14,
    description: 'Builds strong cell walls, preventing berry cracking and enhancing post-harvest life.',
  },
  {
    key: 'Mg',
    displayName: 'Magnesium (Mg)',
    unit: '%',
    referenceRange: '0.51 – 0.80 %',
    isSafeLimit: false,
    refMin: 0.51,
    refMax: 0.80,
    description: 'Core component of chlorophyll; drives photosynthetic energy production.',
  },
  {
    key: 'S',
    displayName: 'Sulfur (S)',
    unit: '%',
    referenceRange: '0.14 – 0.27 %',
    isSafeLimit: false,
    refMin: 0.14,
    refMax: 0.27,
    description: 'Integral for amino acid synthesis, enzyme function, and natural disease resistance.',
  },
  {
    key: 'Fe',
    displayName: 'Iron (Fe)',
    unit: 'ppm',
    referenceRange: '40 – 80 ppm',
    isSafeLimit: false,
    refMin: 40,
    refMax: 80,
    description: 'Micronutrient required for chlorophyll formation; deficiency causes interveinal chlorosis.',
  },
  {
    key: 'Mn',
    displayName: 'Manganese (Mn)',
    unit: 'ppm',
    referenceRange: '40 – 100 ppm',
    isSafeLimit: false,
    refMin: 40,
    refMax: 100,
    description: 'Activates enzymatic pathways and aids in nitrogen assimilation and photosynthesis.',
  },
  {
    key: 'Zn',
    displayName: 'Zinc (Zn)',
    unit: 'ppm',
    referenceRange: '40 – 100 ppm',
    isSafeLimit: false,
    refMin: 40,
    refMax: 100,
    description: 'Vital for auxin synthesis, internode elongation, and regular cluster set.',
  },
  {
    key: 'Cu',
    displayName: 'Copper (Cu)',
    unit: 'ppm',
    referenceRange: '5.01 – 10.00 ppm',
    isSafeLimit: false,
    refMin: 5.01,
    refMax: 10.00,
    description: 'Participates in lignin formation and electron transport in plant respiration.',
  },
  {
    key: 'Boron',
    displayName: 'Boron (B)',
    unit: 'ppm',
    referenceRange: '30 – 70 ppm',
    isSafeLimit: false,
    refMin: 30,
    refMax: 70,
    description: 'Critical for pollen viability, berry set, sugar translocation, and shoot tips.',
  },
  {
    key: 'Mo',
    displayName: 'Molybdenum (Mo)',
    unit: 'ppm',
    referenceRange: '0.25 – 0.50 ppm',
    isSafeLimit: false,
    refMin: 0.25,
    refMax: 0.50,
    description: 'Cofactor for nitrate reductase; indispensable for plant nitrogen utilization.',
  },
  {
    key: 'Na',
    displayName: 'Sodium (Na)',
    unit: '%',
    referenceRange: 'Less than 0.5 %',
    isSafeLimit: true,
    safeLimit: 0.5,
    description: 'Potentially phytotoxic ion; elevated levels indicate soil or irrigation salinity stress.',
  },
  {
    key: 'Cl',
    displayName: 'Chloride (Cl)',
    unit: '%',
    referenceRange: 'Less than 0.5 %',
    isSafeLimit: true,
    safeLimit: 0.5,
    description: 'Essential in micro-quantities; excess causes leaf burn and reduced berry quality.',
  },
];
